### ISSUE TITLE
Validator crashes on validation

### ISSUE THREAD

**Issue by koorchik** [asholok/python-validator-livr#3]
http://livr-playground.tk/#%7B%22rules%22%3A%22%7B%5Cn%20%20flag%3A%20%7Bone_of%3A%20%5Btrue%2C%20false%5D%7D%2C%5Cn%20%20login%3A%20'email'%2C%5Cn%20%20link%3A%20'url'%2C%5Cn%20%20list%3A%20%7Blist_of%3A%20%5B%7Bnested_object%3A%20%7B%7D%7D%5D%7D%5Cn%7D%22%2C%22data%22%3A%22%7B%5Cn%20%20flag%3A%20true%2C%5Cn%20%20login%3A%20'a%20%40gmail.com'%2C%5Cn%20%20link%3A%20'http%3A%2F%2Fgoogle'%2C%5Cn%20%20list%3A%20%5B%5B%5D%5D%5Cn%7D%22%7D

http://livr-playground.tk/#%7B%22rules%22%3A%22%7B%5Cn%20%20flag%3A%20%7Bone_of%3A%20%5Btrue%2C%20false%5D%7D%2C%5Cn%7D%22%2C%22data%22%3A%22%7B%5Cn%20%20flag%3A%20%5C%22test%5C%22%2C%5Cn%7D%22%7D

**Comment by asholok** [comment]
Please follow python-LIVR instructions and python syntax.

**Comment by DanielHreben** [comment]
Next example fails:

``` python
#!/usr/bin/env python3

from LIVR import Validator

inputData = {'test': True}
rules     = {'test': {'one_of': [True, False]}}

validator  = Validator.Validator(rules)

outputData = validator.validate(inputData)
errors     = validator.get_errors()

result = {'errors': errors} if errors else {'output': outputData}

print( result )
```

But if just wrap  `[True, False]` to additional `[]` it works (See sample below).  

Additional info:
[Live sample](http://livr-playground.tk/#%7B%22rules%22%3A%22%7B%5C%22flag%5C%22%3A%20%7B%5C%22one_of%5C%22%3A%20%5B%5Btrue%2C%20false%5D%5D%7D%7D%22%2C%22data%22%3A%22%7B%5C%22flag%5C%22%3A%20true%7D%22%7D)
[Python code used in livr-playground.tk](https://github.com/SDSWanderer/multy-livr-playground/blob/master/realisations/Python/validate.py)

Livr-spec quote:

> // new syntax (introduced in v0.4)
> { first_name: {'one_of': ['Anton', 'Igor']} }
> 
> // old syntax
> { first_name: {'one_of': [['Anton', 'Igor']]} }

**Comment by asholok** [comment]
Ok. Fair enough. I missed this feature to do.
