### ISSUE TITLE
Email is always required

### ISSUE THREAD

**Issue by DanielHreben** [asholok/python-validator-livr#5]
http://livr-playground.tk/#%7B%22rules%22%3A%22%7B%5Cn%20%20%20%20login%3A%20'email'%5Cn%7D%22%2C%22input%22%3A%22%7B%7D%22%7D

**Comment by DanielHreben** [comment]
@asholok  Please, let me known when fix will be available on PyPi

**Comment by asholok** [comment]
My code act exactly to test_suite requirements 
https://github.com/koorchik/LIVR/tree/master/test_suite/negative/16-email

**Comment by DanielHreben** [comment]
No, [here](https://github.com/koorchik/LIVR/blob/master/test_suite/negative/16-email/errors.json) is no error for `empty_field`
