### ISSUE TITLE
Python bug with one_of rule

### ISSUE THREAD

**Issue by koorchik** [asholok/python-validator-livr#7]
http://livr-playground.tk/#%7B%22rules%22%3A%22%7B%5Cn%20%20flag%3A%20%7Bone_of%3A%20%5B%5C%22false%5C%22%5D%7D%5Cn%7D%22%2C%22data%22%3A%22%7B%5Cn%20%20flag%3A%20%5B%5D%5Cn%7D%22%7D

**Comment by asholok** [comment]
Done adapted in 2.0 version
