### ISSUE TITLE
Bug - nested object should remove fields which does not have validation described

### ISSUE THREAD

**Issue by koorchik** [asholok/python-validator-livr#9]
See here - http://livr-multi-playground.webbylab.com/#%7B%22rules%22%3A%22%7Bobj%3A%20%7B'nested_object'%20%3A%20%7Bv%3A'not_empty'%7D%7D%7D%22%2C%22input%22%3A%22%7Bobj%3A%7Bb%3A%20'must%20be%20removed!'%7D%7D%22%7D

**Comment by asholok** [comment]
Adapted in 2.0 version
